### ISSUE TITLE
Please provide a FV3-202305-public release that aligns with fv3 and shield_physics

### ISSUE THREAD

**Issue by StevePny** [NOAA-GFDL/SHiELD_build#33]
**Is your feature request related to a problem? Please describe.**
There is not a public release of SHiELD_build that matches the FV3-202305-public releases for the GFDL_atmos_cubed_sphere and SHiELD_physics repos. It is not immediately obvious which FMS version to use, and what location to look for the coupler_main.F90 file, among other things, to match the build tested at GFDL.

**Describe the solution you'd like**
Please tag the commit used for tests of the FV3-202305-public GFDL_atmos_cubed_sphere and SHiELD_physics tagged here as a public release.

**Comment by laurenchilutti** [comment]
Hi Steve,  I will make a tag of the repository today.  Thank you for bringing this to our attention.

**Comment by StevePny** [comment]
Thanks @laurenchilutti, at the moment I'm using commit 3ed236c859e83b13f8d9b1d8eac47218a318d8cf from June 7, but that's just a guess.

**Comment by laurenchilutti** [comment]
That June 7th commit will be the one that aligns with the release of 202305.  I have tagged this commit as [FV3-202305-public](https://github.com/NOAA-GFDL/SHiELD_build/releases/tag/FV3-202305-public).  

 As described in the release description: The FV3-202305-public release of SHiELD_build is compatible with the FV3-202305-public releases of GFDL_atmos_cubed_sphere, SHiELD_physics, and atmos_drivers pair as well as the 2023.01 releases of FMS and FMScoupler.  

If you would like to use any features from FMS 2023.02 with the last public release, you will need to use the atmos_drivers 2023.02 tag.
