### ISSUE TITLE
Add `Stellar` as a supported build environment

### ISSUE THREAD

**Issue by spencerkclark** [NOAA-GFDL/SHiELD_build#35]
`SHiELD_build` is the canonical way to build SHiELD on various platforms.  [Princeton's Stellar cluster](https://researchcomputing.princeton.edu/systems/stellar), supported by CIMES, is a machine that may be increasingly used over time.  @kaiyuan-cheng has already run several important SHiELD simulations on Stellar, and @tlhsieh is planning on running some more.  Would it be appropriate to add Stellar as a supported environment, at least in `site/environment.intel.sh`?

cc: @lharris4

**Comment by bensonr** [comment]
I think it makes sense to have that as a valid option.  Will you be keeping it up to date as the stellar dev environment is updated by installations and/or removals?

**Comment by spencerkclark** [comment]
Sounds good — yes, I can do my best to keep it up to date.

**Comment by spencerkclark** [comment]
Sounds good — yes, I can do my best to keep it up to date, though it could be useful for others to be involved in this as well.  Part of my motivation for starting this conversation was to ask @kaiyuan-cheng for the setup he used for the PIRE runs, which I think would be a good starting point to codify in this repository.

@kaiyuan-cheng no rush, but if you can either point me to the environment you used on Stellar I can make an initial pull request (or you are welcome to make one yourself if you have time).  Thanks!
