### ISSUE TITLE
pushd in /bin/sh does not work

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/SHiELD_build#6]
The script `Build/mk_scripts/MAKE_libFMS` has the shebang `#!/bin/sh` and fails because of the use of pushd which is not native to posix shell.  The other scripts in this directory are using `#!/bin/bash`, so this shebang in `Build/mk_scripts/MAKE_libFMS` should be updated.

**Comment by laurenchilutti** [comment]
Resolved by PR #12
